---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: testing

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt-mirror::default]
      - recipe[apt-mirror::nginx]
    attributes:
